const {test,expect}=require('@playwright/test');
async function setup(page){
 const state={size:'2',max:['10.12349','9.98765'],fail:false},posted=[];
 const meta={universe:[{name:'ETH',szDecimals:4,maxLeverage:20},{name:'BTC',szDecimals:5,maxLeverage:40}]};
 const spot={tokens:[{name:'USDC',index:0,szDecimals:2},{name:'HYPE',index:1,szDecimals:2}],universe:[{name:'@0',tokens:[1,0],index:0}]};
 const ctx={markPx:'2500',oraclePx:'2500',prevDayPx:'2550',dayNtlVlm:'125000000',openInterest:'50000',funding:'0.0001'};
 await page.route('**/info',async r=>{const q=r.request().postDataJSON();let data=[];
 if(q.type==='meta')data=meta;else if(q.type==='spotMeta')data=spot;
 else if(q.type==='metaAndAssetCtxs')data=[meta,[ctx,ctx]];else if(q.type==='spotMetaAndAssetCtxs')data=[spot,[ctx]];
 else if(q.type==='activeAssetData'){if(state.fail)return r.fulfill({status:503,body:'Unavailable'});data={coin:q.coin,user:q.user,leverage:{type:'cross',value:5},maxTradeSzs:state.max,availableToTrade:['5000','4000'],markPx:'2500'};}
 else if(q.type==='clearinghouseState')data={marginSummary:{accountValue:'10000'},withdrawable:'5000',assetPositions:state.size==='0'?[]:[{position:{coin:'ETH',szi:state.size,entryPx:'2450',leverage:{type:'cross',value:5},marginUsed:'1000',unrealizedPnl:'100',cumFunding:{sinceOpen:'-0.1'}}}]};
 else if(q.type==='spotClearinghouseState')data={balances:[]};
 else if(q.type==='candleSnapshot')data=Array.from({length:80},(_,i)=>({t:Date.now()-(80-i)*60000,o:'2490',h:'2510',l:'2480',c:String(2490+i%20),v:'100'}));
 await r.fulfill({json:data});});
 await page.route('**/exchange',r=>{posted.push(r.request().postDataJSON());return r.fulfill({json:{status:'ok',response:{type:'order',data:{statuses:[{resting:{oid:42}}]}}}});});
 await page.addInitScript(()=>{window.calls=[];window.listeners={};window.fakeChain='0x66eee';window.ethereum={on(k,fn){window.listeners[k]=fn;},removeListener(){},async request(q){window.calls.push(q);if(['eth_accounts','eth_requestAccounts'].includes(q.method))return ['0x1111111111111111111111111111111111111111'];if(q.method==='eth_chainId')return window.fakeChain;if(q.method==='wallet_switchEthereumChain'){window.fakeChain=q.params[0].chainId;return null;}if(q.method==='eth_signTypedData_v4')return '0x'+'11'.repeat(64)+'1b';throw Error(q.method);}};
 window.WebSocket=class{constructor(){this.readyState=1;setTimeout(()=>this.onopen?.(),0);}send(s){const q=JSON.parse(s);if(q.subscription?.type==='l2Book')this.timer=setInterval(()=>{if(!window.stopBook)this.onmessage?.({data:JSON.stringify({channel:'l2Book',data:{coin:q.subscription.coin,time:Date.now(),levels:[Array.from({length:5},(_,i)=>({px:String(2499-i),sz:String(3+i)})),Array.from({length:5},(_,i)=>({px:String(2501+i),sz:String(4+i)}))]}})});},300);}close(){clearInterval(this.timer);this.readyState=3;}};});
 await page.goto('/web/#markets');await expect(page.locator('#fastOrderBar')).toBeVisible();
 return {state,posted};
}
async function connect(page,net='testnet'){await page.locator('#marketNetwork').selectOption(net);await page.locator('#tradeConnect').click();await expect(page.locator('[data-size-pct="50"]')).toBeEnabled();}
test('complete page bootstrap, disconnected locks and responsive layout',async({page})=>{const errors=[];page.on('pageerror',e=>errors.push(e.message));await setup(page);await expect(page.locator('#futuresLong')).toBeDisabled();await expect(page.locator('[data-account-tab=positions]')).toHaveText('Positions (—)');for(const width of [320,390,430,1280]){await page.setViewportSize({width,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);if(width<=680){const a=await page.locator('.order-ticket').boundingBox(),b=await page.locator('.depth').boundingBox();expect(a.x+a.width).toBeLessThanOrEqual(b.x);await page.locator('#futuresChart summary').click();await expect(page.locator('#marketCanvas')).toBeVisible();await page.locator('#futuresChart summary').click();}}expect(errors).toEqual([]);});
test('quick types send the input event and Open can undo Close',async({page})=>{await setup(page);await connect(page);await page.locator('[data-fast-type=Market]').click();await expect(page.locator('#tradePriceField')).toBeHidden();await page.locator('[data-intent=close]').click();await expect(page.locator('#tradeReduce')).toBeChecked();await expect(page.locator('#tradeSide')).toHaveValue('sell');await expect(page.locator('#tradeSize')).toHaveValue('2');await page.locator('[data-size-pct="25"]').click();await expect(page.locator('#tradeSize')).toHaveValue('0.5');await page.locator('[data-intent=open]').click();await expect(page.locator('#tradeReduce')).not.toBeChecked();});
test('percent sizing uses venue side limits, precision and applied leverage',async({page})=>{await setup(page);await connect(page);await page.locator('[data-fast-type=Market]').click();await page.locator('[data-size-pct="50"]').click();await expect(page.locator('#tradeSize')).toHaveValue('4.9605');await page.locator('[data-fast-side=sell]').click();await expect(page.locator('#tradeSize')).toHaveValue('4.8939');await page.locator('#tradeLeverage').fill('20');await expect(page.locator('[data-size-pct="100"]')).toBeDisabled();await expect(page.locator('#tradeSize')).toHaveValue('4.8939');await expect(page.locator('#futuresSizingStatus')).toContainText('Apply margin/leverage');});
test('large action buttons open the original review without signing, mainnet acknowledgement remains',async({page})=>{const {posted}=await setup(page);await connect(page,'mainnet');await page.locator('[data-fast-type=Market]').click();await page.locator('#tradeSize').fill('1');await page.locator('#futuresShort').click();await expect(page.locator('#tradeDialog')).toBeVisible();await expect(page.locator('#tradeSummary')).toContainText('Sell / Short');await expect(page.locator('#tradeSubmit')).toBeDisabled();expect(await page.evaluate(()=>window.calls.filter(x=>/sign|send/i.test(x.method)).length)).toBe(0);expect(posted).toHaveLength(0);await expect(page.locator('[data-intent=open]')).toBeDisabled();await page.locator('#tradeClose').click();await expect(page.locator('[data-intent=open]')).toBeEnabled();});
test('TP/SL shortcut produces the actual standalone reduce-only trigger payload',async({page})=>{const {posted}=await setup(page);await connect(page);await page.locator('[data-fast-type=Stop]').click();await expect(page.locator('#tradeTriggerField')).toBeVisible();await page.locator('#tradeTrigger').fill('2400');await page.locator('#futuresLong').click();await expect(page.locator('#tradeSummary')).toContainText('Trigger: 2400');await page.locator('#tradeSubmit').click();await expect.poll(()=>posted.length).toBe(1);expect(posted[0].action.orders[0]).toMatchObject({b:false,r:true,s:'2',t:{trigger:{triggerPx:'2400',tpsl:'sl',isMarket:true}}});});
test('no-position, unavailable sizes and spot never get fake MAX sizing',async({page})=>{const {state}=await setup(page);state.size='0';state.max=null;await page.locator('#marketNetwork').selectOption('testnet');await page.locator('#tradeConnect').click();await expect(page.locator('#futuresSizingStatus')).toContainText('Venue size limits unavailable');await expect(page.locator('[data-size-pct="100"]')).toBeDisabled();await expect(page.locator('[data-fast-type=Stop]')).toBeDisabled();await expect(page.locator('[data-account-tab=positions]')).toHaveText('Positions (0)');await page.locator('#marketType').selectOption('spot');await expect(page.locator('[data-intent=close]')).toBeDisabled();await expect(page.locator('[data-fast-type=TakeProfit]')).toBeDisabled();await expect(page.locator('#tradeLeveragePanel')).toBeHidden();});
test('stale book and wallet changes lock new buttons',async({page})=>{await setup(page);await connect(page);await page.evaluate(()=>window.stopBook=true);await expect(page.locator('#futuresLong')).toBeDisabled({timeout:10000});await expect(page.locator('[data-size-pct="50"]')).toBeDisabled();await page.evaluate(()=>window.listeners.accountsChanged?.());await expect(page.locator('#futuresSizingStatus')).toContainText('Connect');});
test('counts, mark price, book ratio and mobile screenshot',async({page})=>{await setup(page);await connect(page);await page.setViewportSize({width:390,height:844});await page.locator('[data-fast-type=Market]').click();await expect(page.locator('[data-account-tab=positions]')).toHaveText('Positions (1)');await expect(page.locator('[data-account-tab=orders]')).toHaveText('Open orders (0)');await expect(page.locator('#futuresBookPrice')).toHaveText('2,500');await expect(page.locator('#futuresBidShare')).toContainText('%');await page.screenshot({path:'test-results/futures-v2-mobile.png',fullPage:true});});
