const {test,expect}=require('@playwright/test');
test('testnet order signing, rejection handling and network-change lock',async({page})=>{
 const posted=[];
 await page.route('**/info',async r=>{const q=r.request().postDataJSON();let data;
 if(q.type==='meta')data={universe:[{name:'ETH',szDecimals:4,maxLeverage:20}]};else if(['openOrders','frontendOpenOrders','userFills','userFunding'].includes(q.type))data=[];else if(q.type==='activeAssetData')data={coin:'ETH',leverage:{type:'cross',value:5},availableToTrade:['1000','1000'],markPx:'21'};else if(['metaAndAssetCtxs','spotMetaAndAssetCtxs'].includes(q.type))data=[{universe:[]},[]];else if(q.type==='clearinghouseState')data={marginSummary:{accountValue:'1000'},assetPositions:[]};else if(q.type==='spotClearinghouseState')data={balances:[]};else data=[{t:Date.now()-60000,o:20,h:22,l:19,c:21,v:100}];await r.fulfill({json:data})});
 await page.route('**/exchange',r=>{posted.push({url:r.request().url(),data:r.request().postDataJSON()});return r.fulfill({json:{status:'ok',response:{type:'order',data:{statuses:[{error:'Insufficient margin'}]}}}})});
 await page.addInitScript(()=>{window.calls=[];window.ethereum={on(){},removeListener(){},async request(x){window.calls.push(x);if(x.method==='eth_accounts'||x.method==='eth_requestAccounts')return ['0x1111111111111111111111111111111111111111'];if(x.method==='eth_chainId')return '0x66eee';if(x.method==='wallet_switchEthereumChain')return null;if(x.method==='eth_signTypedData_v4')return '0x'+'11'.repeat(64)+'1b';throw Error(x.method)}};
 window.WebSocket=class{constructor(){this.readyState=1;setTimeout(()=>this.onopen?.(),0)}send(s){const q=JSON.parse(s);if(q.subscription?.type==='l2Book'){this.timer=setInterval(()=>this.onmessage?.({data:JSON.stringify({channel:'l2Book',data:{coin:q.subscription.coin,time:Date.now(),levels:[[{px:'20',sz:'3'}],[{px:'21',sz:'4'}]]}})}),300)}}close(){clearInterval(this.timer);this.readyState=3}};
 });
 await page.goto('/web/');await page.getByRole('button',{name:'Trade',exact:true}).click();await expect(page.locator('#tradeReview')).toBeDisabled();await page.locator('#marketNetwork').selectOption('testnet');await page.locator('#tradeConnect').click();await expect(page.locator('#tradeAccount')).toContainText('111111');
 await expect(page.locator('#tradeReview')).toBeEnabled();await page.locator('#tradePrice').fill('20');await page.locator('#tradeSize').fill('1');await page.locator('#tradeReview').click();await expect(page.locator('#tradeDialog')).toBeVisible();await page.locator('#tradeSubmit').click();await expect(page.locator('#tradeStatus')).toContainText('Insufficient margin');expect(posted).toHaveLength(1);expect(posted[0].url).toContain('hyperliquid-testnet');expect(posted[0].data.action.orders[0].a).toBe(0);expect(posted[0].data.action.orders[0].s).toBe('1');
 const calls=await page.evaluate(()=>window.calls);const signed=calls.find(c=>c.method==='eth_signTypedData_v4');expect(JSON.parse(signed.params[1]).message.source).toBe('b');
 await page.locator('#marketNetwork').selectOption('mainnet');await expect(page.locator('#tradeReview')).toBeDisabled();
});
test('explicit OKX selection uses only the requested provider',async({page})=>{
 await page.addInitScript(()=>{window.used=[];window.ethereum={request(){window.used.push('other');throw Error('Wrong provider')}};window.okxwallet={request(x){window.used.push(x.method);throw Error('User rejected')}}});
 await page.goto('/web/#markets');await page.locator('#walletProvider').selectOption('okx');await page.locator('#tradeConnect').click();await expect(page.locator('#tradeStatus')).toContainText('User rejected');expect(await page.evaluate(()=>window.used)).toEqual(['eth_requestAccounts']);await expect(page.locator('#tradeReview')).toBeDisabled();
});


test('account change inside signing prompt never posts an order',async({page})=>{
 const posted=[];
 await page.route('**/info',async r=>{const q=r.request().postDataJSON();let data;
 if(q.type==='meta')data={universe:[{name:'ETH',szDecimals:4,maxLeverage:20}]};else if(['openOrders','frontendOpenOrders','userFills','userFunding'].includes(q.type))data=[];else if(q.type==='activeAssetData')data={coin:'ETH',leverage:{type:'cross',value:5},availableToTrade:['1000','1000'],markPx:'21'};else if(['metaAndAssetCtxs','spotMetaAndAssetCtxs'].includes(q.type))data=[{universe:[]},[]];else if(q.type==='clearinghouseState')data={marginSummary:{accountValue:'1000'},assetPositions:[]};else if(q.type==='spotClearinghouseState')data={balances:[]};else data=[{t:Date.now()-60000,o:20,h:22,l:19,c:21,v:100}];await r.fulfill({json:data})});
 await page.route('**/exchange',r=>{posted.push({url:r.request().url(),data:r.request().postDataJSON()});return r.fulfill({json:{status:'ok',response:{type:'order',data:{statuses:[{error:'Insufficient margin'}]}}}})});
 await page.addInitScript(()=>{window.calls=[];window.ethereum={on(){},removeListener(){},async request(x){window.calls.push(x);if(x.method==='eth_accounts'||x.method==='eth_requestAccounts')return [window.signChanged?'0x2222222222222222222222222222222222222222':'0x1111111111111111111111111111111111111111'];if(x.method==='eth_chainId')return '0x66eee';if(x.method==='wallet_switchEthereumChain')return null;if(x.method==='eth_signTypedData_v4'){window.signChanged=true;return '0x'+'11'.repeat(64)+'1b';}throw Error(x.method)}};
 window.WebSocket=class{constructor(){this.readyState=1;setTimeout(()=>this.onopen?.(),0)}send(s){const q=JSON.parse(s);if(q.subscription?.type==='l2Book'){this.timer=setInterval(()=>this.onmessage?.({data:JSON.stringify({channel:'l2Book',data:{coin:q.subscription.coin,time:Date.now(),levels:[[{px:'20',sz:'3'}],[{px:'21',sz:'4'}]]}})}),300)}}close(){clearInterval(this.timer);this.readyState=3}};
 });
 await page.goto('/web/');await page.getByRole('button',{name:'Trade',exact:true}).click();await expect(page.locator('#tradeReview')).toBeDisabled();await page.locator('#marketNetwork').selectOption('testnet');await page.locator('#tradeConnect').click();await expect(page.locator('#tradeAccount')).toContainText('111111');
 await expect(page.locator('#tradeReview')).toBeEnabled();await page.locator('#tradePrice').fill('20');await page.locator('#tradeSize').fill('1');await page.locator('#tradeReview').click();await expect(page.locator('#tradeDialog')).toBeVisible();await page.locator('#tradeSubmit').click();await expect(page.locator('#tradeStatus')).toContainText('Wallet account or network changed');expect(posted).toHaveLength(0);
});
