// Presentation-only helpers that drive the existing validated order form.
const q=s=>document.querySelector(s), by=id=>document.getElementById(id);
function setSide(side){const el=by('tradeSide');if(!el)return;el.value=side;el.dispatchEvent(new Event('change',{bubbles:true}));document.querySelectorAll('[data-fast-side]').forEach(b=>b.classList.toggle('active',b.dataset.fastSide===side));}
function setType(type){const el=by('tradeType');if(!el)return;el.value=type;el.dispatchEvent(new Event('change',{bubbles:true}));document.querySelectorAll('[data-fast-type]').forEach(b=>b.classList.toggle('active',b.dataset.fastType===type));}
function setPercent(p){const size=by('tradeSize'),avail=by('tradeAvailable'),price=by('marketMark');if(!size||!avail)return;const a=Number((avail.textContent||'').replace(/[^0-9.]/g,'')),px=Number((price?.textContent||'').replace(/,/g,''));const lev=Number(by('tradeLeverage')?.value)||1;if(!(a>0)||!(px>0))return;size.value=(a*lev*p/100/px).toFixed(5).replace(/0+$/,'').replace(/\.$/,'');size.dispatchEvent(new Event('input',{bubbles:true}));document.querySelectorAll('[data-size-pct]').forEach(b=>b.classList.toggle('active',Number(b.dataset.sizePct)===p));}
function mount(){const ticket=q('.order-ticket');if(!ticket||by('fastOrderBar'))return;
 const bar=document.createElement('div');bar.id='fastOrderBar';bar.className='fast-order-bar';bar.innerHTML=`<div class="fast-row fast-open-close"><button class="active" type="button">Open</button><button type="button" data-close-mode>Close / Reduce</button></div><div class="fast-row"><button type="button" data-fast-side="buy">Long</button><button type="button" data-fast-side="sell">Short</button></div><div class="fast-row"><button type="button" data-fast-type="Market">Market</button><button type="button" data-fast-type="Gtc">Limit</button><button type="button" data-fast-type="Stop">SL</button><button type="button" data-fast-type="TakeProfit">TP</button></div>`;ticket.insertBefore(bar,ticket.firstChild.nextSibling);
 const size=by('tradeSize');if(size){const wrap=size.closest('label');const slider=document.createElement('div');slider.className='fast-size';slider.innerHTML=`<div class="fast-size-track" role="group" aria-label="Quick size"><button type="button" data-size-pct="25">25%</button><button type="button" data-size-pct="50">50%</button><button type="button" data-size-pct="75">75%</button><button type="button" data-size-pct="100">MAX</button></div>`;wrap.after(slider);}
 document.addEventListener('click',e=>{const side=e.target.closest('[data-fast-side]');if(side)setSide(side.dataset.fastSide);const type=e.target.closest('[data-fast-type]');if(type)setType(type.dataset.fastType);const pct=e.target.closest('[data-size-pct]');if(pct)setPercent(Number(pct.dataset.sizePct));const close=e.target.closest('[data-close-mode]');if(close){by('tradeReduce').checked=true;by('tradeReduce').dispatchEvent(new Event('change',{bubbles:true}));document.querySelector('.fast-open-close button:first-child')?.classList.remove('active');close.classList.add('active');}});
 setSide(by('tradeSide')?.value||'buy');setType(by('tradeType')?.value||'Gtc');
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount);else mount();
