import QRCode from 'qrcode';
import jsQR from 'jsqr';
import {USDT_ROUTES,usdtRoute} from './usdt-registry.js';
import {units,canonical,paymentRequest,parsePayment,explorerTx,explorerAccount} from './usdt-core.js';
import {providersFor,connectUsdt,adapterFor,watchSession,subscribeSession} from './usdt-providers.js';
import {UsdtTransferService} from './usdt-service.js';
import {readJournal} from './usdt-journal.js';
const $=id=>document.getElementById(id);
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const errorText=e=>String(e?.shortMessage||e?.message||'Request could not be completed.').replace(/[\u0000-\u001f\u202a-\u202e\u2066-\u2069]/g,' ').slice(0,350);
const sessions=new Map(),subscriptions=new Map(),balances=new Map();let routeId='ethereum',view='receive',epoch=0,busy=false,review=null,service=null,qrPayload='',opener=null;
const route=()=>usdtRoute(routeId),session=()=>sessions.get(route().family),isOpen=()=>$('usdtDialog')?.open;
function status(text,failed=false){const el=$('usdtStatus');if(el){el.textContent=text;el.className='w-inline-status '+(failed?'error':'');}}
function checkContext(me){if(!isOpen()||me!==epoch)throw Error('View, wallet or network changed. Review again.');}
function wire(id,fn,event='click'){const el=$(id);if(el)el.addEventListener(event,e=>Promise.resolve().then(()=>fn(e)).catch(err=>{status(errorText(err),true);window.toast?.(errorText(err));}));}
function noAccount(){return '<p class="w-note">Connect a compatible wallet, or enter your public address for receive-only access. BELTRIX does not create or store private keys.</p>';}
function mount(){
 if($('usdtDialog'))return;
 const css=document.createElement('link');css.rel='stylesheet';css.href=new URL('./usdt.css',document.baseURI).href;document.head.append(css);
 const dialog=document.createElement('dialog');dialog.id='usdtDialog';dialog.className='wallet-modal usdt-modal';dialog.setAttribute('aria-labelledby','usdtTitle');
 dialog.innerHTML='<div class="w-modal-head"><h2 id="usdtTitle">USDT wallet</h2><button id="usdtClose" type="button" class="w-icon-button" aria-label="Close USDT wallet">✕</button></div><div id="usdtContent"></div><p id="usdtStatus" class="w-inline-status" role="status"></p>';
 document.body.append(dialog);
 const closed=()=>{epoch++;review=null;service=null;qrPayload='';opener?.focus?.({preventScroll:true});};
 wire('usdtClose',()=>dialog.close());dialog.addEventListener('close',closed);
 dialog.addEventListener('click',e=>{if(e.target===dialog){const b=dialog.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)dialog.close();}});
}
export function openUsdt(mode='receive',source=null){
 mount();if(busy){window.toast?.('A USDT request is still in progress. Do not repeat it.');return;}
 opener=source||document.activeElement;view=['receive','send','history','networks'].includes(mode)?mode:'receive';epoch++;render();if(!isOpen())$('usdtDialog').showModal();
}
function invalidate(family){
 subscriptions.get(family)?.();subscriptions.delete(family);sessions.delete(family);for(const r of USDT_ROUTES.filter(r=>r.family===family))balances.delete(r.id);
 epoch++;review=null;service=null;if(isOpen()){render();status('Wallet account or network changed. Reconnect and review. Check History for any request already sent.',true);}
}
function remember(s){subscriptions.get(s.family)?.();for(const r of USDT_ROUTES.filter(r=>r.family===s.family))balances.delete(r.id);sessions.set(s.family,s);if(s.provider)subscriptions.set(s.family,subscribeSession(s,()=>invalidate(s.family)));}
async function connect(){
 if(busy)return;const choice=providersFor(routeId).find(x=>x.id===$('usdtProvider').value);if(!choice)throw Error('No compatible wallet found. Open BELTRIX in your wallet browser or extension.');
 const me=epoch;busy=true;status('Waiting for wallet connection and selected-network verification…');$('usdtConnect').disabled=true;
 try{const s=await connectUsdt(routeId,choice);checkContext(me);remember(s);epoch++;render();await refreshSelected();}finally{busy=false;if($('usdtConnect'))$('usdtConnect').disabled=false;}
}
async function refreshSelected(){
 const s=session();if(!s)return;const r=route(),me=epoch;status('Reading '+r.symbol+' and '+r.native+' balances…');
 try{const data=await adapterFor(r.id,s).balances();if(sessions.get(r.family)!==s)return;balances.set(r.id,{...data,updated:Date.now(),account:s.account});if(me===epoch&&isOpen()){updateBalance();status('Balance read from '+r.name+'.');}}
 catch(e){balances.set(r.id,{error:errorText(e),account:s.account});if(me===epoch&&isOpen()){updateBalance();status('Balance unavailable: '+errorText(e),true);}}
}
function updateBalance(){const b=balances.get(routeId),el=$('usdtBalance');if(!el)return;el.textContent=!session()?'Not connected':!b?'Not checked':b.error?'Unavailable — '+b.error:units(b.raw,route().decimals)+' '+route().symbol+' · '+units(b.native,route().nativeDecimals)+' '+route().native+' for fees';}
function render(){
 if(!$('usdtContent'))return;review=null;service=null;qrPayload='';const r=route(),s=session(),providers=providersFor(routeId);
 $('usdtContent').innerHTML=`<div class="usdt-route-note"><b>Mainnet · same-network wallet transfers</b><span>Not trading-account funding. No automatic swap or cross-chain transfer.</span></div><label class="w-field">USDT network<select id="usdtNetwork">${USDT_ROUTES.map(n=>`<option value="${n.id}" ${n.id===routeId?'selected':''}>${esc(n.name)} · ${n.symbol}</option>`).join('')}</select></label><details class="usdt-token-details"><summary>${esc(r.representation)}</summary><code class="usdt-contract">${esc(r.token)}</code></details>${s?`<details class="usdt-session-details"><summary>${esc(s.name)} · ${esc(s.account.slice(0,6))}…${esc(s.account.slice(-4))} · Change</summary>`:''}<div class="usdt-connection"><label class="w-field">Signing wallet<select id="usdtProvider">${providers.length?providers.map(p=>`<option value="${esc(p.id)}">${esc(p.name)}</option>`).join(''):'<option value="">No compatible wallet detected</option>'}</select></label><button id="usdtConnect" class="w-secondary" type="button">${s?.provider?'Reconnect':'Connect'}</button></div>${s?`<div class="usdt-account"><span>${esc(s.name)}${s.provider?'':' · receive only'}</span><code>${esc(s.account)}</code><button id="usdtDisconnect" type="button" class="w-text-button">Clear connection</button></div>`:noAccount()}<details class="usdt-watch"><summary>Use a public address for receiving / watching</summary><label class="w-field">Address on ${esc(r.name)}<input id="usdtWatchAddress" autocomplete="off" spellcheck="false" placeholder="${r.family==='evm'?'0x…':r.family==='tron'?'T…':'Solana public address'}"></label><button id="usdtWatch" class="w-secondary" type="button">Use public address</button></details>${s?'</details>':''}<div class="usdt-balance-row"><span id="usdtBalance"></span><button id="usdtRefresh" class="w-text-button" type="button" ${s?'':'disabled'}>Refresh</button></div><div class="usdt-tabs" role="tablist" aria-label="USDT tools">${[['receive','Receive'],['send','Send'],['history','History'],['networks','Balances']].map(([id,label])=>`<button type="button" role="tab" aria-selected="${view===id}" data-usdt-tab="${id}">${label}</button>`).join('')}</div><section id="usdtPanel" role="tabpanel"></section>`;
 wire('usdtNetwork',()=>{if(busy){$('usdtNetwork').value=routeId;throw Error('Complete the current request before changing networks.');}routeId=$('usdtNetwork').value;epoch++;render();},'change');
 wire('usdtConnect',connect);wire('usdtDisconnect',()=>{if(busy)throw Error('A wallet request is still open.');invalidate(r.family);});
 wire('usdtWatch',()=>{if(busy)return;const s=watchSession(routeId,$('usdtWatchAddress').value);remember(s);epoch++;render();refreshSelected();});
 wire('usdtRefresh',refreshSelected);
 $('usdtContent').querySelectorAll('[data-usdt-tab]').forEach(b=>b.addEventListener('click',()=>{if(busy){status('Complete the current request first.');return;}view=b.dataset.usdtTab;epoch++;render();}));
 updateBalance();status('');renderPanel();
}
function renderPanel(){if(view==='receive')receive();else if(view==='send')send();else if(view==='history')history();else networkBalances();}
function receive(){
 const s=session(),r=route();$('usdtPanel').innerHTML=s?`<p class="w-note"><b>Receive ${esc(r.symbol)} on ${esc(r.name)} only.</b> Verify the sender supports this exact token contract. The same EVM address does not mean the same network.</p><label class="w-field">QR format<select id="usdtQrMode"><option value="address">Address only · exchange-compatible</option>${r.family!=='tron'?'<option value="payment">Payment request · supported wallets</option>':''}</select></label><label class="w-field" id="usdtQrAmountField" hidden>Requested amount (optional)<input id="usdtQrAmount" inputmode="decimal" placeholder="0.00"></label><canvas id="usdtQR" aria-label="Receive address QR code"></canvas><code id="usdtQrAddress" class="usdt-full-address">${esc(s.account)}</code><div class="usdt-buttons"><button id="usdtCopyAddress" class="w-secondary" type="button">Copy address</button><button id="usdtSaveQR" class="w-secondary" type="button">Save QR</button><button id="usdtShareQR" class="w-secondary" type="button">Share</button></div><p class="w-note" id="usdtQrNote">Address-only QR does not encode a network or amount. Select ${esc(r.name)} in the sending application.</p>`:noAccount();
 if(!s)return;
 const me=epoch;let drawing=0;const draw=async()=>{const tick=++drawing;qrPayload='';const pay=$('usdtQrMode').value==='payment';$('usdtQrAmountField').hidden=!pay;const payload=paymentRequest(routeId,s.account,pay?$('usdtQrAmount').value:'',!pay);await QRCode.toCanvas($('usdtQR'),payload,{width:240,margin:4,errorCorrectionLevel:'M'});checkContext(me);if(tick!==drawing)return;qrPayload=payload;$('usdtQrNote').textContent=pay?'Payment request encodes the exact network/token. Unsupported senders should use address-only mode.':'Address-only QR does not encode the network or amount. Select '+r.name+' in the sending application.';};
 draw().catch(e=>status(errorText(e),true));wire('usdtQrMode',draw,'change');wire('usdtQrAmount',draw,'input');
 wire('usdtCopyAddress',async()=>{await navigator.clipboard.writeText(s.account);status('Address copied. Select the same network in the sender.');});
 wire('usdtSaveQR',async()=>{if(!qrPayload)throw Error('Generate a valid QR first.');const c=document.createElement('canvas');c.width=720;c.height=940;const g=c.getContext('2d');g.fillStyle='#fff';g.fillRect(0,0,c.width,c.height);const qr=document.createElement('canvas');await QRCode.toCanvas(qr,qrPayload,{width:640,margin:4,errorCorrectionLevel:'M'});g.drawImage(qr,40,40);g.fillStyle='#111';g.font='bold 25px sans-serif';g.fillText(r.symbol+' · '+r.name,35,720);g.font='20px monospace';for(const [i,line] of s.account.match(/.{1,48}/g).entries())g.fillText(line,35,760+i*28);g.font='16px sans-serif';g.fillText('Mainnet — verify network and token before sending.',35,845);g.fillText(r.token,35,880);const a=document.createElement('a');a.href=c.toDataURL('image/png');a.download='BELTRIX-'+routeId+'-'+r.symbol+'-receive.png';a.click();});
 wire('usdtShareQR',async()=>{if(!qrPayload)throw Error('Generate a valid QR first.');const text=r.symbol+' on '+r.name+'\nAddress: '+s.account+'\nToken: '+r.token+'\n'+qrPayload;if(navigator.share)await navigator.share({title:'BELTRIX receive '+r.symbol,text});else{await navigator.clipboard.writeText(text);status('Network, token and address copied.');}});
}
function send(){
 const s=session(),r=route();$('usdtPanel').innerHTML=`<p class="w-note">Send ${esc(r.symbol)} to the <b>same network</b>. ${esc(r.native)} is required for fees. USDT is not converted to USDC.</p><label class="w-field">Recipient address<input id="usdtRecipient" spellcheck="false" autocomplete="off" placeholder="Address on ${esc(r.name)}"></label><details><summary>Paste or read a QR payment request</summary><label class="w-field">Address / payment text<textarea id="usdtPayment" rows="2" maxlength="1000"></textarea></label><div class="usdt-buttons"><button id="usdtImportText" class="w-secondary" type="button">Use text</button><label class="w-secondary usdt-file">Read QR image<input id="usdtQrFile" type="file" accept="image/png,image/jpeg,image/webp"></label></div></details><label class="w-field">Amount in ${esc(r.symbol)}<input id="usdtAmount" inputmode="decimal" autocomplete="off" placeholder="0.00"></label><button id="usdtMax" class="w-text-button" type="button">Use token balance</button><p class="w-note">Token maximum does not spend your native gas balance.</p><label class="w-check"><input type="checkbox" id="usdtRecipientAck"><span>I checked the full address and the recipient supports ${esc(r.name)} and this exact ${esc(r.symbol)} contract.</span></label><button id="usdtReview" class="w-primary full" type="button" ${s?.provider?'':'disabled'}>Review transfer</button>${s?.provider?'':'<p class="w-note">Connect a signing wallet on the selected network to send. Watch-only addresses cannot send.</p>'}`;
 const imported=text=>{const p=parsePayment(routeId,text);$('usdtRecipient').value=p.recipient;if(p.amount)$('usdtAmount').value=p.amount;$('usdtRecipientAck').checked=false;status('Payment details filled only. Check the recipient, amount and network before review.');};
 wire('usdtImportText',()=>imported($('usdtPayment').value));
 wire('usdtQrFile',async e=>{const file=e.target.files?.[0];if(!file)return;if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw Error('Choose a PNG, JPEG or WebP QR image.');if(file.size>8000000)throw Error('QR image must be below 8 MB.');const me=epoch,bitmap=await createImageBitmap(file);try{if(bitmap.width*bitmap.height>24000000)throw Error('QR image dimensions are too large.');const scale=Math.min(1,1600/Math.max(bitmap.width,bitmap.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(bitmap.width*scale));c.height=Math.max(1,Math.round(bitmap.height*scale));const g=c.getContext('2d',{willReadFrequently:true});g.drawImage(bitmap,0,0,c.width,c.height);const img=g.getImageData(0,0,c.width,c.height),decoded=jsQR(img.data,img.width,img.height);checkContext(me);if(!decoded)throw Error('No readable QR found. Paste the address instead.');imported(decoded.data);}finally{bitmap.close();e.target.value='';}},'change');
 wire('usdtMax',async()=>{await refreshSelected();const b=balances.get(routeId);if(!b||b.error||b.raw<=0n)throw Error('A positive, current token balance is required.');$('usdtAmount').value=units(b.raw,r.decimals);});
 wire('usdtReview',async()=>{
  if(busy)return;if(!$('usdtRecipientAck').checked)throw Error('Confirm the recipient network and token first.');const to=$('usdtRecipient').value,input=$('usdtAmount').value,me=epoch,selected=session();if(!selected?.provider)throw Error('Connect a signing wallet.');
  busy=true;$('usdtReview').disabled=true;status('Checking network, balances, recipient and fees; simulating the exact transfer…');
  try{service=new UsdtTransferService(adapterFor(routeId,selected),{isCurrent:()=>isOpen()&&epoch===me&&session()===selected});review=await service.prepare(to,input);checkContext(me);showReview();}
  finally{busy=false;if($('usdtReview'))$('usdtReview').disabled=!session()?.provider;}
 });
}
function showReview(){
 const r=route(),s=session(),x=review;$('usdtPanel').innerHTML=`<h3>Review ${esc(r.symbol)} transfer</h3><div class="w-review-amount">${esc(units(x.quantity,r.decimals))} ${r.symbol}</div><dl class="w-review-lines"><div><dt>Network</dt><dd>${esc(r.name)} · Mainnet</dd></div><div><dt>From</dt><dd>${esc(s.account)}</dd></div><div><dt>Recipient</dt><dd>${esc(x.recipient)}</dd></div><div><dt>Token</dt><dd>${esc(r.token)}</dd></div><div><dt>Network fee / budget</dt><dd>${esc(units(x.fee,r.nativeDecimals))} ${r.native}</dd></div>${x.extraFee?`<div><dt>New token-account rent</dt><dd>${units(x.extraFee,r.nativeDecimals)} ${r.native}</dd></div>`:''}</dl><p class="w-note">${esc(x.feeLabel)}${x.contractRecipient?'<br>Recipient is a smart contract. Confirm that it accepts this asset.':''}${x.recipientDetail?'<br>'+esc(x.recipientDetail):''}</p><p class="w-note">Review expires in at most 60 seconds. Closing this window does not cancel a request already sent to your wallet or the network.</p><label class="w-check"><input id="usdtSignAck" type="checkbox"><span>I reviewed the full recipient, network, token, amount and fees. This uses real mainnet assets.</span></label><button id="usdtSign" class="w-primary full" type="button" disabled>Confirm in wallet</button><button id="usdtEdit" class="w-secondary full" type="button">Back to form</button>`;
 wire('usdtSignAck',()=>{$('usdtSign').disabled=!$('usdtSignAck').checked||busy;},'change');
 wire('usdtEdit',()=>{if(busy)return;epoch++;render();});
 wire('usdtSign',async()=>{
  if(busy||!$('usdtSignAck')?.checked)return;busy=true;$('usdtSign').disabled=true;status('Review the external wallet request. Do not submit again while it is pending.');const me=epoch,svc=service,x=review;
  try{const row=await svc.execute(x);if(me===epoch&&isOpen()){view='history';epoch++;render();status('Transaction submitted, not yet confirmed. Use Check status in History.');}return row;}
  catch(e){if(me===epoch&&isOpen()){view='history';epoch++;render();status(errorText(e),true);}throw e;}
  finally{busy=false;}
 });
 status('Review prepared. No transaction has been sent.');
}
function history(){
 const s=session();if(!s){$('usdtPanel').innerHTML=noAccount();return;}
 let rows;try{rows=readJournal(localStorage).filter(x=>x.route===routeId&&x.account===canonical(routeId,s.account));}catch(e){$('usdtPanel').innerHTML='<p class="w-error">'+esc(errorText(e))+'</p>';return;}
 $('usdtPanel').innerHTML=`<p class="w-note">Transfers requested from this browser. Submitted / Unknown is not proof of arrival. Checks are read-only and never resend.</p><div id="usdtLocalHistory">${rows.length?rows.map(x=>`<article class="usdt-history-row"><b>${esc(units(x.quantity,route().decimals))} ${route().symbol}</b><span>${esc(x.status)}</span><code>${esc(x.recipient)}</code>${x.hash?`<a href="${esc(explorerTx(routeId,x.hash))}" target="_blank" rel="noopener noreferrer">View transaction ↗</a>`:''}<p class="w-note">${esc(x.detail||'Awaiting confirmation')}</p><input aria-label="Original transaction reference" data-usdt-hash="${esc(x.id)}" placeholder="${x.hash?'Recorded reference':'Original transaction hash / signature'}" value="${esc(x.hash||'')}" ${x.hash?'readonly':''}><button class="w-secondary" type="button" data-usdt-check="${esc(x.id)}">Check status</button></article>`).join(''):'<p class="w-note">No USDT transfers requested from this browser for this account and network.</p>'}</div><button id="usdtChainHistory" class="w-secondary full" type="button">Load recent on-chain activity</button><div id="usdtRecent"></div><a class="w-link" href="${esc(explorerAccount(routeId,s.account))}" target="_blank" rel="noopener noreferrer">Open full account explorer ↗</a>`;
 $('usdtPanel').querySelectorAll('[data-usdt-check]').forEach(b=>b.addEventListener('click',async()=>{if(busy)return;busy=true;b.disabled=true;const me=epoch;try{const svc=new UsdtTransferService(adapterFor(routeId,s));const input=[...$('usdtPanel').querySelectorAll('[data-usdt-hash]')].find(x=>x.dataset.usdtHash===b.dataset.usdtCheck);await svc.check(b.dataset.usdtCheck,input.value.trim());if(me===epoch&&isOpen()){history();status('Checked the original transaction. No transaction was resent.');}}catch(e){status(errorText(e),true);}finally{busy=false;b.disabled=false;}}));
 wire('usdtChainHistory',async()=>{const me=epoch;status('Loading limited recent on-chain activity…');const result=await adapterFor(routeId,s).recent();checkContext(me);$('usdtRecent').innerHTML='<p class="w-note">'+esc(result.detail||result.scope||'Recent activity only; not complete history.')+'</p>'+result.rows.map(x=>`<div class="usdt-history-row"><span>${esc(x.direction||(x.incoming?'Received':'Sent'))} ${esc(units(x.quantity||x.amount,route().decimals))} ${route().symbol}</span><a href="${esc(explorerTx(routeId,x.hash))}" target="_blank" rel="noopener noreferrer">Transaction ↗</a></div>`).join('');status('Recent activity loaded. Use the explorer for older or missing records.');});
}
function networkBalances(){
 $('usdtPanel').innerHTML='<p class="w-note">Different chains have separate balances. EVM networks share the connected EVM address; TRON and Solana require their own addresses. Unavailable data is not shown as zero.</p>'+USDT_ROUTES.map(r=>`<div class="usdt-network-row"><b>${esc(r.name)}</b><span id="usdtRow-${r.id}">${sessions.has(r.family)?'Not checked':'No address connected'}</span><button type="button" class="w-text-button" data-usdt-route="${r.id}">Choose</button></div>`).join('')+'<button id="usdtAllBalances" class="w-secondary full" type="button">Refresh connected addresses</button>';
 for(const b of $('usdtPanel').querySelectorAll('[data-usdt-route]'))b.addEventListener('click',()=>{if(busy)return;routeId=b.dataset.usdtRoute;view='receive';epoch++;render();});
 wire('usdtAllBalances',async()=>{const me=epoch;$('usdtAllBalances').disabled=true;try{for(const r of USDT_ROUTES){const s=sessions.get(r.family);if(!s)continue;try{const b=await adapterFor(r.id,s).balances();checkContext(me);balances.set(r.id,{...b,account:s.account,updated:Date.now()});$('usdtRow-'+r.id).textContent=units(b.raw,r.decimals)+' '+r.symbol;}catch(e){if(me!==epoch||!isOpen())return;$('usdtRow-'+r.id).textContent='Unavailable — '+errorText(e);}}}finally{if($('usdtAllBalances'))$('usdtAllBalances').disabled=false;}});
}
