export const icons={
 search:'<circle cx="10.5" cy="10.5" r="6.5"/><path d="m16 16 5 5"/>',
 send:'<path d="M12 21V3m-7 7 7-7 7 7"/>',receive:'<path d="M12 3v18m-7-7 7 7 7-7"/>',
 history:'<path d="M13 3H4v18h10M8 7h5M8 11h2"/><circle cx="17" cy="15" r="6"/><path d="M17 12v3l2 1"/>',
 grid:'<path d="M3 3h6v6H3zM15 3h6v6h-6zM3 15h6v6H3zM15 15h6v6h-6z"/>',
 globe:'<circle cx="12" cy="12" r="9"/><ellipse cx="12" cy="12" rx="4" ry="9"/><path d="M3 12h18"/>',
 bell:'<path d="M5 16V9a7 7 0 0 1 14 0v7l2 2H3zM9 21h6"/>',
 copy:'<path d="M8 8h12v13H8zM16 8V3H3v13h5"/>',chevron:'<path d="m8 10 4 4 4-4"/>',
 arrow:'<path d="M5 12h14m-6-6 6 6-6 6"/>',external:'<path d="M14 3h7v7M21 3 10 14M9 5H3v16h16v-6"/>',
 wallet:'<path d="M4 6h16v15H4zM4 6V4l12-2v4M15 11h7v6h-7z"/><path d="M18 14h.01"/>',
 compass:'<circle cx="12" cy="12" r="9"/><path d="m16 8-2 6-6 2 2-6z"/>',
 swap:'<path d="M3 7h18m-5-5 5 5-5 5M21 17H3m5-5-5 5 5 5"/>',
 defi:'<path d="m12 2 9 5v10l-9 5-9-5V7zM7 14l3-4 4 4 3-5"/>',
 boost:'<path d="m14 4 6-1-1 6-8 8-4-4zM7 13l-4 1v5l5-1M11 17l-1 4H5v-5"/><circle cx="15.5" cy="7.5" r="1"/>',
 close:'<path d="m6 6 12 12M18 6 6 18"/>',refresh:'<path d="M20 7V2l-3 3a9 9 0 1 0 3 12M20 2h-5"/>',
 shield:'<path d="m12 2 8 4v6c0 5-8 10-8 10S4 17 4 12V6zM8 12l3 3 5-6"/>',
 eye:'<path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12z"/><circle cx="12" cy="12" r="3"/>',
 link:'<path d="m9 15 6-6M8 17l-1 1a4 4 0 0 1-6-6l5-5a4 4 0 0 1 6 0M16 7l1-1a4 4 0 0 1 6 6l-5 5a4 4 0 0 1-6 0"/>',
 plus:'<path d="M12 4v16M4 12h16"/>',check:'<path d="m4 12 5 5L20 6"/>',settings:'<path d="M4 7h16M4 17h16"/><circle cx="9" cy="7" r="3"/><circle cx="16" cy="17" r="3"/>',
 star:'<path d="m12 2 3 6 7 1-5 5 1 7-6-3-6 3 1-7-5-5 7-1z"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M3 16v5h18v-5"/>'
};
export const icon=(name,extra='')=>`<svg class="w-icon ${extra}" viewBox="0 0 24 24" aria-hidden="true">${icons[name]||icons.wallet}</svg>`;
export function mountWallet(){
 const container=document.querySelector('.app');
 container.insertAdjacentHTML('beforeend',`
 <main id="wallet" class="page wallet-home" aria-label="Wallet">
  <div class="w-toolbar"><button class="w-icon-button" data-action="more" aria-label="All features">${icon('grid')}</button><button class="w-search-button" data-action="search" aria-label="Search assets, addresses and DApps">${icon('search')}<span>Crypto, stocks, address, DApp</span></button><button class="w-icon-button" data-action="preferences" aria-label="Wallet preferences">${icon('globe')}</button><button class="w-icon-button" data-action="notifications" aria-label="Notifications">${icon('bell')}<span id="wUnread" class="w-unread" hidden></span></button></div>
  <div class="w-account-row"><button id="wAccount" class="w-account-button" data-action="accounts"><span class="w-identicon" aria-hidden="true"></span><span id="wAccountName" class="w-account-name">My wallet</span>${icon('chevron')}</button><button id="wCopyAddress" class="w-icon-button" data-action="copy-address" aria-label="Copy wallet address" disabled>${icon('copy')}</button><button id="wNetwork" class="w-chain-button" data-action="networks"><span id="wNetworkDot" class="w-network-dot"></span><span id="wNetworkName">Ethereum</span>${icon('chevron')}</button></div>
  <div class="w-mini-label" id="wAccountMode">Connect a wallet to view your assets</div>
  <div class="w-hero"><div class="w-hero-value"><div class="w-value-caption">Estimated balance <button class="w-icon-button" data-action="hide-balances" aria-label="Show or hide balances" style="padding:0">${icon('eye')}</button></div><div id="wTotal" class="w-total private-value">—</div><div id="wTotalMeta" class="w-hero-meta">Your keys stay in your wallet.</div></div><div class="w-pixel-mark" aria-hidden="true"><img src="./beltrix-symbol.svg" alt="" width="280" height="330"></div></div>
  <div class="w-actions"><button class="w-action" data-action="send"><span class="w-action-circle">${icon('send','large')}</span>Send</button><button class="w-action" data-action="receive"><span class="w-action-circle">${icon('receive','large')}</span>Receive</button><button class="w-action" data-action="history"><span class="w-action-circle">${icon('history','large')}</span>History</button><button class="w-action" data-action="more"><span class="w-action-circle">${icon('grid','large')}</span>More</button></div>
  <button class="w-banner" data-action="open-defi"><span><strong>Put your wallet to work</strong><small>Explore DeFi markets, staking & on-chain tools</small></span>${icon('boost')}</button>
  <div class="w-tabs" role="tablist" aria-label="Wallet asset categories"><button class="w-tab active" role="tab" aria-selected="true" data-tab="crypto">Crypto</button><button class="w-tab" role="tab" aria-selected="false" data-tab="stocks">Stocks</button><button class="w-tab" role="tab" aria-selected="false" data-tab="positions">DeFi</button><button class="w-tab" role="tab" aria-selected="false" data-tab="dapps">DApps</button><button class="w-tab" role="tab" aria-selected="false" data-tab="approvals">Approvals</button></div>
  <section id="wPanel-crypto" class="w-tab-panel" role="tabpanel"><div class="w-list-head"><span id="wAssetCount">Assets on Ethereum</span><div><button class="w-text-button" data-action="import-token">+ Import token</button> <button class="w-icon-button" data-action="refresh" aria-label="Refresh wallet" style="display:inline-flex;padding:6px">${icon('refresh')}</button></div></div><div id="wAssetStatus" class="w-inline-status" role="status"></div><div id="wAssets" class="w-token-list"></div><p class="w-note" id="wPriceNote"></p></section>
  <section id="wPanel-stocks" class="w-tab-panel" role="tabpanel" hidden><div class="w-list-head"><span>Equity-linked perpetual markets</span><button class="w-text-button" data-action="refresh-stocks">Refresh</button></div><p class="w-note">Live Hyperliquid builder markets. These are derivatives, not stock ownership. Prices can differ from stock exchanges.</p><div id="wStocks"></div></section>
  <section id="wPanel-positions" class="w-tab-panel" role="tabpanel" hidden><div class="w-list-head"><span>Hyperliquid account</span><button class="w-text-button" data-action="hyper-account">Open account</button></div><div class="w-section-card"><h2>Trading & DeFi positions</h2><p>View Hyperliquid spot balances, perpetual positions, fills and deposits. Open the protocol apps below to manage lending and staking positions.</p><button class="w-primary" data-action="hyper-account">View trading account</button></div><div id="wPositionDapps" class="w-dapp-grid"></div></section>
  <section id="wPanel-dapps" class="w-tab-panel" role="tabpanel" hidden><div class="w-list-head"><span>Explore on-chain apps</span><button class="w-text-button" data-action="explore">View all</button></div><div id="wHomeDapps" class="w-dapp-grid"></div></section>
  <section id="wPanel-approvals" class="w-tab-panel" role="tabpanel" hidden><div class="w-section-card"><h2>Stay in control</h2><p>Inspect a token's spending allowance and revoke it with your connected wallet. A recent on-chain scan covers the last 2,000 blocks; older and NFT approvals require a broader explorer.</p><button class="w-primary" data-action="approvals">Manage approvals</button></div></section>
 </main>
 <main id="explore" class="page wallet-subpage"><div class="w-subtitle"><div><h1>Explore</h1><p>Your gateway to on-chain apps.</p></div><button class="w-icon-button" data-action="search" aria-label="Search DApps">${icon('search')}</button></div><div class="w-pills" id="wDappFilters"><button data-dapp-filter="All" class="active">All</button><button data-dapp-filter="Trade">Trade</button><button data-dapp-filter="DeFi">DeFi</button><button data-dapp-filter="Bridge">Bridge</button><button data-dapp-filter="Security">Security</button></div><div id="wExploreDapps" class="w-dapp-grid"></div><div class="w-section-card"><h2>Your watchlist</h2><p>Save a public address, switch accounts and view transfers without connecting a wallet.</p><button class="w-secondary" data-action="accounts">Manage accounts</button></div><p class="w-note">Apps open on their own domains. Review the domain and every wallet request.</p></main>
 <main id="defi" class="page wallet-subpage"><div class="w-subtitle"><div><h1>DeFi</h1><p>Lending, staking and account positions.</p></div><button class="w-icon-button" data-action="refresh-yields" aria-label="Refresh DeFi markets">${icon('refresh')}</button></div><div id="wDefiDapps" class="w-dapp-grid"></div><div class="w-section-card"><div class="w-row"><h2>Market rates</h2><span class="w-badge neutral">DeFiLlama</span></div><p>Variable estimated APY, reported by the data provider. Rates are not guaranteed; deposits carry protocol and market risk.</p><div id="wPools"></div><p id="wPoolsUpdated" class="w-note"></p></div><button class="w-secondary full" data-action="hyper-account">View Hyperliquid balances & history</button></main>
 <main id="boost" class="page wallet-subpage"><div class="w-subtitle"><div><h1>Boost</h1><p>Make your next move.</p></div>${icon('boost','large')}</div><button class="w-banner" data-action="open-defi"><span><strong>Explore earning opportunities</strong><small>Live DeFi market rates, with the details in view</small></span>${icon('arrow')}</button><div class="w-quick-grid"><button data-action="bridge">${icon('swap')}Bridge</button><button data-action="approvals">${icon('shield')}Check approvals</button><button data-action="hyper-account">${icon('defi')}Trading account</button></div><div class="w-section-card"><h2>Start with testnet funds</h2><p>Practice Hyperliquid spot and perpetual orders before using a production venue. Choose Mainnet for real orders or Testnet to practice.</p><button class="w-primary" data-action="testnet-trade">Open testnet trading</button></div><div class="w-section-card"><h2>Keep track of every move</h2><p>Filter sends and receives, open transaction details and export loaded history to CSV.</p><button class="w-secondary" data-action="history">Open history</button></div></main>`);
 const nav=document.querySelector('.nav');
 nav.insertAdjacentHTML('afterbegin','<button data-page="wallet">Wallet</button><button data-page="explore">Explore</button>');
 document.body.insertAdjacentHTML('beforeend',`<nav class="bottom-nav" aria-label="Wallet navigation"><button data-page="wallet">${icon('wallet')}Wallet</button><button data-page="explore">${icon('compass')}Explore</button><button data-page="markets"><span class="dex-circle">${icon('swap')}</span>DEX</button><button data-page="defi">${icon('defi')}DeFi</button><button data-page="boost">${icon('boost')}Boost</button></nav><dialog id="wDialog" class="wallet-modal"><div class="w-modal-head"><h2 id="wDialogTitle"></h2><button id="wClose" class="w-icon-button" aria-label="Close wallet dialog">${icon('close')}</button></div><div id="wDialogBody"></div></dialog>`);
}
